---
title: "191108_HW5"
author: "Gavin Ko"
date: "11/4/2019"
output: github_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

# Problem 1

Firstly, generate the iris data with NA values.
```{r generate dataset with NAs}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20) , NA) ) %>%
  mutate(Species = as.character(Species))
```


```{r function construction}
nasavior = function(x) {

# for numeric part
  if (is.numeric(x) == T) {
    # take the mean outside of the iteration so that it didn't constantly changes as we fill in NAs
    # rounding to 2 digits under decimal
    mean = round( mean(x, na.rm = T), digits = 2)
    
    for (i in 1:length(x)) {
      
        if (is.na(x[[i]]) == T) {
          x[[i]] = mean
        }
    }
    
# for species
  } else if (is.character(x) == T) {
    
      for (i in 1:length(x)) {
      
        if (is.na(x[[i]]) == T) {
          x[[i]] = "virginica"
        }
      }
    }
# return the results   
  x
}

```

After we construct the `nasavior` function, we can further apply it to the `iris_with_missing` dataset. 

```{r function mapping}
iris_with_missing %>% 
  map_df(~nasavior(.x))

```

# Problem 2

## Dataframe with all file names

```{r collect all the data names}

```


